
export enum KeyCode {
    BackSpace = 8,
    Tab = 9,
    Enter = 13,
    Shift = 16,
    Ctrl,
    Alt,
    PauseOrBreak,
    CapsLock,
    Escape = 27,
    Space = 32,
    PageUp = 33,
    PageDown,
    End,
    Home,
    LeftArrow,
    UpArrow,
    RightArrow,
    DownArrow,
    Insert = 45,
    Delete,
    N0 = 48,
    N1, N2, N3, N4, N5, N6, N7, N8, N9,
    $A = 65,
    $B, $C, $D, $E, $F, $G, $H, $I, $J, $K, 
    $L, $M, $N, $O, $P, $Q, $R,
    $S, $T, $U, $V, $W, $X, $Y, $Z,
    LeftWindowKey, RightWindowKey,
    SelectKey,
    Multiply = 106,
    Add = 107,
    Subtract = 109,
    DecimalPoint = 100,
    Divide = 111,
    F1 = 112,
    F2, F3, F4, F5, F6,
    F7, F8, F9, F10, F11, F12,
    NumLock = 144,
    Semicolon = 145,
    EqualSign = 187,
    Comma, Dash, Period, ForwardSlash,
    GraveAccent,
    OpenBraket = 219,
    BackSlash,
    CloseBraket,
    SingleQuote,
}
